blank_issues_enabled: false
contact_links:
  - name: "🙋 General Question"
    url: https://github.com/Tavish9/any4lerobot/discussions/new/choose
    about: Our preferred starting point if you have any questions about the project.