_attn_implementation_autoset:
    value: true
_name_or_path:
    value: /virtual_lab/rlwrld/david/.cache/huggingface/hub/models--nvidia--GR00T-N1.5-3B/snapshots/3c235401cb51575b3f091e68de96dc0785de971d
_wandb:
    value:
        cli_version: 0.18.0
        m:
            - "1": train/global_step
              "6":
                - 3
              "7": []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 2
                - 3
                - 11
                - 12
                - 41
                - 49
                - 51
                - 55
                - 63
                - 71
                - 80
                - 83
                - 98
            "2":
                - 1
                - 2
                - 3
                - 11
                - 12
                - 41
                - 49
                - 51
                - 55
                - 63
                - 71
                - 80
                - 83
                - 98
            "3":
                - 7
                - 13
                - 19
                - 23
                - 55
                - 62
                - 66
            "4": 3.10.18
            "5": 0.18.0
            "6": 4.51.3
            "8":
                - 5
            "9":
                "1": transformers_trainer
            "12": 0.18.0
            "13": linux-x86_64
accelerator_config:
    value:
        dispatch_batches: null
        even_batches: true
        gradient_accumulation_kwargs: null
        non_blocking: false
        split_batches: false
        use_seedable_sampler: true
action_dim:
    value: 21
action_head_cfg:
    value:
        action_dim: 21
        action_horizon: 16
        add_pos_embed: true
        backbone_embedding_dim: 2048
        diffusion_model_cfg:
            attention_head_dim: 48
            cross_attention_dim: 2048
            dropout: 0.2
            final_dropout: true
            interleave_self_attention: true
            norm_type: ada_norm
            num_attention_heads: 32
            num_layers: 16
            output_dim: 1024
            positional_embeddings: null
        hidden_size: 1024
        input_embedding_dim: 1536
        max_action_dim: 32
        max_state_dim: 64
        model_dtype: float32
        noise_beta_alpha: 1.5
        noise_beta_beta: 1
        noise_s: 0.999
        num_inference_timesteps: 4
        num_target_vision_tokens: 32
        num_timestep_buckets: 1000
        tune_diffusion_model: true
        tune_projector: true
        use_vlln: true
        vl_self_attention_cfg:
            attention_head_dim: 64
            dropout: 0.2
            final_dropout: true
            num_attention_heads: 32
            num_layers: 4
            positional_embeddings: null
action_horizon:
    value: 16
adafactor:
    value: false
adam_beta1:
    value: 0.95
adam_beta2:
    value: 0.999
adam_epsilon:
    value: 1e-08
add_cross_attention:
    value: false
architectures:
    value:
        - GR00T_N1_5
attn_implementation:
    value: null
auto_find_batch_size:
    value: false
average_tokens_across_devices:
    value: false
backbone_cfg:
    value:
        eagle_path: NVEagle/eagle_er-qwen3_1_7B-Siglip2_400M_stage1_5_128gpu_er_v7_1mlp_nops
        load_bf16: false
        project_to_dim: null
        reproject_vision: false
        select_layer: 12
        tune_llm: false
        tune_visual: true
        use_flash_attention: true
bad_words_ids:
    value: null
batch_eval_metrics:
    value: false
begin_suppress_tokens:
    value: null
bf16:
    value: true
bf16_full_eval:
    value: false
bos_token_id:
    value: null
chunk_size_feed_forward:
    value: 0
compute_dtype:
    value: bfloat16
cross_attention_hidden_size:
    value: null
data_seed:
    value: null
dataloader_drop_last:
    value: false
dataloader_num_workers:
    value: 8
dataloader_persistent_workers:
    value: true
dataloader_pin_memory:
    value: false
dataloader_prefetch_factor:
    value: null
ddp_backend:
    value: null
ddp_broadcast_buffers:
    value: null
ddp_bucket_cap_mb:
    value: 100
ddp_find_unused_parameters:
    value: false
ddp_timeout:
    value: 1800
debug:
    value: []
decoder_start_token_id:
    value: null
deepspeed:
    value: ""
disable_tqdm:
    value: false
diversity_penalty:
    value: 0
do_eval:
    value: false
do_predict:
    value: false
do_sample:
    value: false
do_train:
    value: false
early_stopping:
    value: false
encoder_no_repeat_ngram_size:
    value: 0
eos_token_id:
    value: null
eval_accumulation_steps:
    value: null
eval_delay:
    value: 0
eval_do_concat_batches:
    value: true
eval_on_start:
    value: false
eval_steps:
    value: null
eval_strategy:
    value: "no"
eval_use_gather_object:
    value: false
exponential_decay_length_penalty:
    value: null
finetuning_task:
    value: null
forced_bos_token_id:
    value: null
forced_eos_token_id:
    value: null
fp16:
    value: false
fp16_backend:
    value: auto
fp16_full_eval:
    value: false
fp16_opt_level:
    value: O1
fsdp:
    value: []
fsdp_config:
    value:
        min_num_params: 0
        xla: false
        xla_fsdp_grad_ckpt: false
        xla_fsdp_v2: false
fsdp_min_num_params:
    value: 0
fsdp_transformer_layer_cls_to_wrap:
    value: null
full_determinism:
    value: false
gradient_accumulation_steps:
    value: 1
gradient_checkpointing:
    value: false
gradient_checkpointing_kwargs:
    value: null
greater_is_better:
    value: null
group_by_length:
    value: false
half_precision_backend:
    value: auto
hidden_size:
    value: 2048
hub_always_push:
    value: false
hub_model_id:
    value: null
hub_private_repo:
    value: null
hub_strategy:
    value: every_save
hub_token:
    value: <HUB_TOKEN>
id2label:
    value:
        "0": LABEL_0
        "1": LABEL_1
ignore_data_skip:
    value: false
include_for_metrics:
    value: []
include_inputs_for_metrics:
    value: false
include_num_input_tokens_seen:
    value: false
include_tokens_per_second:
    value: false
is_decoder:
    value: false
is_encoder_decoder:
    value: false
jit_mode_eval:
    value: false
label_names:
    value: null
label_smoothing_factor:
    value: 0
label2id:
    value:
        LABEL_0: 0
        LABEL_1: 1
learning_rate:
    value: 0.0001
length_column_name:
    value: length
length_penalty:
    value: 1
load_best_model_at_end:
    value: false
local_rank:
    value: 0
log_level:
    value: passive
log_level_replica:
    value: warning
log_on_each_node:
    value: true
logging_dir:
    value: ./gr00t/checkpoints/job_1441_gr00t_30_percent_pos_only_right_arm_robot_view/runs/Jul10_19-21-21_worker-node100
logging_first_step:
    value: false
logging_nan_inf_filter:
    value: true
logging_steps:
    value: 10
logging_strategy:
    value: steps
lr_scheduler_type:
    value: cosine
max_grad_norm:
    value: 1
max_length:
    value: 20
max_steps:
    value: 30000
metric_for_best_model:
    value: null
min_length:
    value: 0
model/num_parameters:
    value: 2723212896
model_dtype:
    value: float32
model_type:
    value: gr00t_n1_5
mp_parameters:
    value: ""
neftune_noise_alpha:
    value: null
no_cuda:
    value: false
no_repeat_ngram_size:
    value: 0
num_beam_groups:
    value: 1
num_beams:
    value: 1
num_return_sequences:
    value: 1
num_train_epochs:
    value: 300
optim:
    value: adamw_torch
optim_args:
    value: null
optim_target_modules:
    value: null
output_attentions:
    value: false
output_dir:
    value: ./gr00t/checkpoints/job_1441_gr00t_30_percent_pos_only_right_arm_robot_view
output_hidden_states:
    value: false
output_scores:
    value: false
overwrite_output_dir:
    value: false
pad_token_id:
    value: null
past_index:
    value: -1
per_device_eval_batch_size:
    value: 8
per_device_train_batch_size:
    value: 24
per_gpu_eval_batch_size:
    value: null
per_gpu_train_batch_size:
    value: null
prediction_loss_only:
    value: false
prefix:
    value: null
problem_type:
    value: null
push_to_hub:
    value: false
push_to_hub_model_id:
    value: null
push_to_hub_organization:
    value: null
push_to_hub_token:
    value: <PUSH_TO_HUB_TOKEN>
ray_scope:
    value: last
remove_invalid_values:
    value: false
remove_unused_columns:
    value: false
repetition_penalty:
    value: 1
report_to:
    value:
        - tensorboard
restore_callback_states_from_checkpoint:
    value: false
resume_from_checkpoint:
    value: null
return_dict:
    value: true
return_dict_in_generate:
    value: false
run_name:
    value: ./gr00t/checkpoints/job_1441_gr00t_30_percent_pos_only_right_arm_robot_view
save_on_each_node:
    value: false
save_only_model:
    value: false
save_safetensors:
    value: true
save_steps:
    value: 5000
save_strategy:
    value: steps
save_total_limit:
    value: 8
seed:
    value: 42
sep_token_id:
    value: null
skip_memory_metrics:
    value: true
suppress_tokens:
    value: null
task_specific_params:
    value: null
temperature:
    value: 1
tf_legacy_loss:
    value: false
tf32:
    value: true
tie_encoder_decoder:
    value: false
tie_word_embeddings:
    value: true
tokenizer_class:
    value: null
top_k:
    value: 50
top_p:
    value: 1
torch_compile:
    value: false
torch_compile_backend:
    value: null
torch_compile_mode:
    value: null
torch_dtype:
    value: float32
torch_empty_cache_steps:
    value: null
torchdynamo:
    value: null
torchscript:
    value: false
tp_size:
    value: 0
tpu_metrics_debug:
    value: false
tpu_num_cores:
    value: null
transformers_version:
    value: 4.51.3
typical_p:
    value: 1
use_bfloat16:
    value: false
use_cpu:
    value: false
use_ipex:
    value: false
use_legacy_prediction_loop:
    value: false
use_liger_kernel:
    value: false
use_mps_device:
    value: false
warmup_ratio:
    value: 0.05
warmup_steps:
    value: 0
weight_decay:
    value: 1e-05
